server:
  port: 8008
  contextPath: /order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.230:8002/registry-server/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.1.112:3306/hx_tsh_dep?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: hx_tsh_dep
    password: hx_tsh_dep
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.1.230
    password:
    database: 1
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      timeout: 0
mybatis:
  config-location: C:/config-repo/mybatis-config.xml
logging:
  level:
    root: info
    com:
      tsh:
        microse: debug