server:
  port: 8007
  contextPath: /tsh-mg
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.230:8002/registry-server/eureka/
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    host: 139.129.203.216
    password:
    database: 1
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      timeout: 0
  dubbo:
    application:
      name: annotation-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.tsh.microse